services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-storage:/data
    networks:
      - dev
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redisinsight-storage:/data
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  redisinsight-storage:
    driver: local
  redis-storage:
    driver: local
