apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "discord-bot-operator.fullname" . | quote }}
  labels:
    {{- include "discord-bot-operator.labels" . | nindent 4 }}
rules:
- apiGroups: ["example.com"]
  resources: ["discordbots"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
