apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "discord-bot-operator.fullname" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "discord-bot-operator.fullname" . | quote }}
subjects:
- kind: ServiceAccount
  name: {{ include "discord-bot-operator.fullname" . | quote }}
  namespace: discord-bot-operator
