apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secrets
  namespace: discord-bot
type: Opaque
stringData:
  discordToken: "MTMzNDg5ODQzNDU3NDEyNzE5Nw.GdlAT2.T2rYvqUMVeeczoxd3kzSyztFkaJ34ESvqXPmAo"
