# Redis Configuration
# see: charts/redis/values.yaml
redis:
  fullnameOverride: "redis"

# Bot Cluster Configuration
# see: charts/bot-cluster/values.yaml
bot-cluster:
  fullnameOverride: "bot-cluster"

  sharding:
    reshardInterval: "1h"

  tokenSecretRef:
    envVarName: "DISCORD_TOKEN"
    name: "bot-cluster"
    key: "discordToken"

  container:
    resources:
      requests:
        memory: 256Mi
        cpu: 500m
      limits:
        memory: 512Mi
        cpu: 1000m

  env:
  - name: "REDIS_HOST"
    value: "redis"
  - name: "REDIS_SECURE"
    value: "false"
  - name: "REDIS_PORT"
    value: "6379"
  - name: "REDIS_DATABASE"
    value: "0"
  - name: "LOG_LEVEL"
    value: "info"
