# Redis Configuration
# see: charts/redis/values.yaml
redis:
  fullnameOverride: "redis"

# Bot Cluster Configuration
# see: charts/bot-cluster/values.yaml
bot-cluster:
  fullnameOverride: "bot-cluster"
  tokenSecretRef:
    envVarName: "DISCORD_TOKEN"
    name: "bot-cluster"
    key: "discordToken"
  env:
  - name: "REDIS_HOST"
    value: "redis"
  - name: "REDIS_SECURE"
    value: "false"
  - name: "REDIS_PORT"
    value: "6379"
  - name: "REDIS_DATABASE"
    value: "0"
  - name: "LOG_LEVEL"
    value: "info"
