apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: discordbots.example.com
  labels:
    {{- include "discord-bot-operator.labels" . | nindent 4 }}
spec:
  group: example.com
  names:
    plural: discordbots
    singular: discordbot
    kind: DiscordBotCluster
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              container:
                type: object
                properties:
                  image:
                    type: string
                  imagePullPolicy:
                    type: string
                  httpProbePort:
                    type: integer
                  resources:
                    type: object
                    properties:
                      requests:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                      limits:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
              tokenSecretRef:
                type: object
                properties:
                  envVarName:
                    type: string
                  name:
                    type: string
                  key:
                    type: string
              sharding:
                type: object
                properties:
                  reshardInterval:
                    type: string
                    format: duration
              env:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                    valueFrom:
                      type: object
                      properties:
                        secretKeyRef:
                          type: object
                          properties:
                            name:
                              type: string
                            key:
                              type: string
                        configMapKeyRef:
                          type: object
                          properties:
                            name:
                              type: string
                            key:
                              type: string
              initContainers:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                    resources:
                      type: object
                      properties:
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                    command:
                      type: array
                      items:
                        type: string
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
