apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "discord-bot-operator.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "discord-bot-operator.labels" . | nindent 4 }}
