apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  ports:
    - port: 6379
      protocol: TCP
      targetPort: "redis"
