apiVersion: example.com/v1
kind: DiscordBotCluster
metadata:
  name: {{ include "discord-bot-cluster.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "discord-bot-cluster.labels" . | nindent 4 }}
spec:
  sharding:
    reshardInterval: {{ .Values.sharding.reshardInterval | quote }}
  tokenSecretRef:
    name: {{ .Values.tokenSecretRef.name | quote }}
    key: {{ .Values.tokenSecretRef.key | quote }}
  container:
    image: {{ .Values.container.image | quote }}
    imagePullPolicy: {{ .Values.container.imagePullPolicy | quote }}
  env:
    {{- toYaml .Values.env | nindent 2 }}
