apiVersion: example.com/v1
kind: DiscordBotCluster
metadata:
  name: {{ include "discord-bot-cluster.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "discord-bot-cluster.labels" . | nindent 4 }}
spec:
  sharding:
    reshardInterval: {{ .Values.sharding.reshardInterval | quote }}
  tokenSecretRef:
    name: {{ .Values.tokenSecretRef.name | quote }}
    key: {{ .Values.tokenSecretRef.key | quote }}
initContainers:
  - name: "wait-for-redis"
    image: "busybox:latest"
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - |
      echo "Waiting for Redis to be available at redis:6379..."
      until nc -z redis 6379; do
        echo "Redis not ready yet..."
        sleep 2
      done
      echo "Redis is up!"
  container:
    image: {{ .Values.container.image | quote }}
    imagePullPolicy: {{ .Values.container.imagePullPolicy | quote }}
  env:
    {{- toYaml .Values.env | nindent 2 }}
