apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-token
  namespace: discord-bot
type: Opaque
stringData:
  discordToken: "MTMzNDg5ODQzNDU3NDEyNzE5Nw.GrgW3e.0TxNLx8blcVyD1HrOnWQS-ti8mJpyJPM50zVc4"
